Repository epam/UUI, pull requests merged in 2022-01, with the labels that each got.

#364 [PickerInput]: Fix placeholder ending for single selection mode
  epam-promo/components/pickers/docs/common.tsx
  epam-promo/components/pickers/docs/pickerInput.doc.tsx
  epam-promo/components/pickers/docs/pickerModal.doc.tsx
  loveship/components/pickers/docs/common.tsx
  loveship/components/pickers/docs/pickerInput.doc.tsx
  loveship/components/pickers/docs/pickerList.doc.tsx
  loveship/components/pickers/docs/pickerModal.doc.tsx
  uui-components/src/pickers/PickerBase.tsx
  uui-components/src/pickers/PickerInputBase.tsx
Labels: bug

#365 [NotificationCard]: Added rawProps; Rewrite to FC; Adjust tests
  epam-promo/components/overlays/NotificationCard.tsx
  loveship/components/overlays/NotificationCard.tsx
  loveship/components/overlays/__tests__/NotificationCard.test.tsx
  loveship/components/overlays/__tests__/__snapshots__/NotificationCard.test.tsx.snap
Labels: enhancement

#367 [TextInput, Textarea][Loveship]: Fix color
  loveship/components/inputs/TextArea.scss
  loveship/components/inputs/TextInput.scss
Labels: bug

#366 [Button][Loveship]: Reduce possible colors in property explorer
  app/src/docs/Button.doc.tsx
  app/src/docs/assets/loveship/LoveshipColors.doc.tsx
  loveship/components/buttons/docs/button.doc.tsx
Labels: bug

#371 [Typescript, Amplitude]: Upgrade and remove importing helpers
  app/package.json
  app/src/analyticsEvents/listeners/AmplitudeListener.ts
  app/src/data/codesandbox/package.json
  app/src/docs/examples/contexts/AnalyticsContextBase.example.tsx
  edu-core-routing/urlParser.ts
  loveship/components/datePickers/docs/rangeDatePicker.doc.tsx
  next-app/tsconfig.json
  package.json
  templates/uui-cra-template/template.json
  uui-build/package.json
  uui/helpers/urlParser.ts
  yarn.lock
Labels: feature

#376 [Demo]: Table with footer and summary
  app/src/demo/table/DemoTable.scss
  app/src/demo/table/DemoTable.tsx
  app/src/demo/table/SlidingPanel.scss
  app/src/sandbox/tables/PersonsTable.scss
  app/src/sandbox/tables/PersonsTable.tsx
  app/src/sandbox/tables/PersonsTableDemo.tsx
  app/src/sandbox/tables/columns.tsx
  app/src/sandbox/tables/types.ts
  server/api/testDataApis.js
  server/helpers/generateTestData.js
  uui-docs/src/models/index.ts
Labels: enhancement

#381 [MainMenuSearch]: add IEditableDebouncer
  epam-promo/components/navigation/MainMenu/MainMenuSearch.tsx
  epam-promo/components/navigation/MainMenu/__tests__/MainMenuSearch.test.tsx
Labels: feature

#384 [PickerModal]: renderFooter props fixes
  epam-promo/components/pickers/PickerModal.tsx
  loveship/components/pickers/PickerModal.tsx
  uui-components/src/pickers/PickerModalBase.tsx
Labels: bug

#387 [DemoTable][Sandbox]: Sync footer values with table values
  app/src/sandbox/tables/PersonsTable.tsx
  app/src/sandbox/tables/columns.tsx
Labels: bug

#391 [Hotfix][VirtualList, DataTable]: Config button rendering; Estimatedheight calculation
  app/src/docs/examples/virtualList/Advanced.example.tsx
  app/src/docs/examples/virtualList/AdvancedExample.scss
  uui-components/src/table/DataTableRowContainer.tsx
  uui/hooks/useScrollShadows.ts
Labels: hotfix

#395 [VirtualList, DataTableHeaderCell]: Fix header cell DnD; Fixed cells wrapper flexBasis
  app/src/docs/examples/virtualList/Advanced.example.tsx
  epam-promo/components/tables/DataTableHeaderRow.tsx
  loveship/components/tables/DataTableHeaderRow.tsx
  loveship/components/tables/__tests__/__snapshots__/DataTable.test.tsx.snap
  loveship/components/tables/__tests__/__snapshots__/DataTableHeaderRow.test.tsx.snap
  uui-components/src/table/DataTableRowContainer.tsx
  uui/hooks/useVirtualList.ts
Labels: bug
